In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

#Data
data = {
    'User': ['User1','User2','User3','User4'],
    'Item1': [5,4,3,2],
    'Item2': [4,5,2,3],
    'Item3': [2,3,4,5]
}

#Create a Dataframe and set the index to 'User'
df = pd.DataFrame(data).set_index('User')

#Compute user similarity using cosine similarity
user_similarity = cosine_similarity(df)

print('Cosine_similarity')
print(user_similarity)

#Compute Pearson correlation coefficient matrix
user_similarity_df = df.T.corr(method='pearson')

print('Pearson Similarity')
print(user_similarity_df)

Cosine_similarity
[[1.         0.96976515 0.85813663 0.77384133]
 [0.96976515 1.         0.89288374 0.87177979]
 [0.85813663 0.89288374 1.         0.96396037]
 [0.77384133 0.87177979 0.96396037 1.        ]]
Pearson Similarity
User      User1     User2     User3     User4
User                                         
User1  1.000000  0.654654 -0.654654 -1.000000
User2  0.654654  1.000000 -1.000000 -0.654654
User3 -0.654654 -1.000000  1.000000  0.654654
User4 -1.000000 -0.654654  0.654654  1.000000
